FROM node
RUN mkdir worker

# This command makes `/worker/` the current working directory. You can assume you are 'inside' that directory for all following commands
WORKDIR worker

# TODO: ADD all the application code into /worker
ADD ./Server/Workers /worker
ADD package.json /worker
ADD ./node_modules /worker/node_modules
ADD ./Server/Workers/jobqueue.js /workerserver/jobserver.js
ADD ./Server/Workers/template.js /workerserver/template.js
ADD ./Server/Workers/queue.js /workerserver/queue.js


# TODO: RUN `npm install`
# RUN npm install

# EXPOSE 3000 
# This command allows us to access the web server port from outside the container

CMD ["node", "jobqueue.js"] # `package.json` already provides this command