FROM node
RUN mkdir server
RUN mkdir DB

# This command makes `/server/` the current working directory. You can assume you are 'inside' that directory for all following commands
WORKDIR DB

# TODO: ADD all the application code into /server
ADD ./Server/Controllers /server/Controllers
ADD ./Server/Models /server/Models
ADD ./Server/Workers/email.js /server/Workers/email.js
ADD ./Server/Workers/apikeys.js /server/Workers/apikeys.js


ADD ./Server/server.js /server/server.js

ADD ./DB /DB
ADD ./Server/Routes/ /server/routes
ADD package.json /server
ADD dbpackage.json /DB/package.json
ADD ./node_modules /server/node_modules/


# TODO: RUN `npm install`
 RUN npm install

 WORKDIR ../server

EXPOSE 3000 
# This command allows us to access the web server port from outside the container

CMD ["node", "server.js"] # `package.json` already provides this command