server:
  build: .
  dockerfile: Dockerfile-server
  ports:
   - 80:3000
  environment:
    DEPLOYED: "true"
  links:
   # - redis
   - postgres

workerserver:
  build: .
  dockerfile: Dockerfile-workerserver
  ports:
   - 4568:4568
  environment:
    DEPLOYED: "true"
  links:
   - redis
   - postgres

worker:
  build: .
  dockerfile: Dockerfile-worker
  environment:
    DEPLOYED: "true"
  links:
   - redis
   # - postgres

redis:
  image: redis

postgres:
  image: postgres