FROM node
RUN mkdir workerserver

# This command makes `/workerserver/` the current working directory. You can assume you are 'inside' that directory for all following commands
WORKDIR workerserver

# TODO: ADD all the application code into /worker
ADD ./Server/Workers /workerserver
ADD package.json /workerserver
ADD ./node_modules /workerserver/node_modules
ADD ./Server/Workers/jobserver.js /workerserver/jobserver.js
ADD ./Server/Workers/queue.js /workerserver/queue.js

# TODO: RUN `npm install`
# RUN npm install

 EXPOSE 4568 
# This command allows us to access the web server port from outside the container

CMD ["node", "jobserver.js"] # `package.json` already provides this command